### ISSUE TITLE
Saving  and loading studentModels as separate files

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/PAR#102]
done when: 
  - each student model is saved to its own json file with the username of the student. 
  - the datastore saves a directory containing  only these files, rather than keeping one json filepath
  - datastore has a method to save a specific studentmodel in this fashion

  - datastore has a method to retrieve a studentModel, or return null if that student model file doesn't exist.
  - On requests for student model, if the server didn't find it in the map, and it requests it from the datastore, of not found there, it generates the new one (as it does currently).

**Comment by JohnHunter809** [comment]
2 hrs: setting up file structure and loading from them

**Comment by JohnHunter809** [comment]
2 hrs: JsonDatastore can now save individual students or all of them
-spent time implementing this into the system
