### ISSUE TITLE
system checks whether a questionPool is okay with a certain window size

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/PAR#143]
done when: 
 - a questionPool has a method to check if a window size is okay for all the types in that questionPool
 - a ResponseSet (and the upper studentModel) can provide the current window size
 - the server that creates both can use the to check if questionPool is okay with window size
 - an exception is thrown if the window size and questionPool are incompatible

**Comment by JohnHunter809** [comment]
QuestionPool now has a method to check if a window size is okay for all the types in that questionPool

**Comment by JohnHunter809** [comment]
StudentModel and UserQuestionSet now have getWindowSize() methods. However, the way that the windowSize is set needs to be discussed

**Comment by JohnHunter809** [comment]
At what point is the windowSize determined? In ParServer?
