### ISSUE TITLE
Add attachment questions to the question generator

### ISSUE THREAD

**Issue by kerryannebuckman** [tobydragon/PAR#164]
Done when:
 - question generator can create a pool that has attachment followup questions.

**Comment by JohnHunter809** [comment]
Roadblocks: 
-Where can we get a list of answers to attachment questions from?
-How can we link them to parent structure questions?

**Comment by JohnHunter809** [comment]
All of the functionality has been implemented in EquineQuestionTemplateCreator. However, the question and answer text are bad. Where can we get some realistic attachment questions and answers?
