### ISSUE TITLE
Write complete JS Tests

### ISSUE THREAD

**Issue by CryptoGraphicDragon** [tobydragon/PAR#24]

**Comment by EMurtaghh** [comment]
1.5 hours working on tests

**Comment by CryptoGraphicDragon** [comment]
2 hours writing response tests and learning how to work jasmine

**Comment by EMurtaghh** [comment]
jasmine not recognizing HTML testpages, so certain tests cannot be completed.

**Comment by CryptoGraphicDragon** [comment]
1 hour making sure response sending actually worked

**Comment by EMurtaghh** [comment]
1.5 hours- ReadImageTask tests. reworked readQuestion into gen/display funcs, which needed changes across other functions
