### ISSUE TITLE
Make generic functions to check any question set

### ISSUE THREAD

**Issue by EMurtaghh** [tobydragon/PAR#26]
how to demo: can take any question set on an image task and accurately display correct/incorrect on the question set.

**Comment by EMurtaghh** [comment]
40min, initial tests

**Comment by CryptoGraphicDragon** [comment]
3 hours writing functions to read list of questions and check answers

**Comment by EMurtaghh** [comment]
1hr 20 minutes, functions to handle question display generation

**Comment by EMurtaghh** [comment]
20min- reworked readQuestion to make generic

**Comment by CryptoGraphicDragon** [comment]
2 hours fixing check answers
