### ISSUE TITLE
Send response through JSON from front end

### ISSUE THREAD

**Issue by EMurtaghh** [tobydragon/PAR#27]
how to demo: should be able to have a response and send it via JSON from front end to back end to User Response

**Comment by CryptoGraphicDragon** [comment]
1 hour working on base response functions

**Comment by CryptoGraphicDragon** [comment]
30 min reading tecMap and taking needed aspects

**Comment by CryptoGraphicDragon** [comment]
1 hour fixing the response so it no longer sends errors
