### ISSUE TITLE
create api call to add a new user with a certain cohort

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/PAR#360]
how to demo:
- working tests showing that new users are added to correct cohort
- postman call can create a new, usable user on the live server
  - call to create new user
  - call to getCurrentQuestion for that user
  - call to addTimeSeen for that user
  - call to getCurrentQuestion should return a next question appropriate for the given cohort

**Comment by vkumar825** [comment]
6/10/21

Worked on it for 2 hours.
- Was figuring out the process of the cohortId variable and what to do with it, and how to also add studentId to the JSON file.  

6/11/21

Worked and discussed in the meeting for about 1 hour 30 mins.
- Implemented the addNewUser fully.
- Went over the process of adding studentId to cohort
