### ISSUE TITLE
QuestionHistorySummary complete

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/PAR#377]
how to demo:

Show that tests are passing checking the:
- seen
- respondedTo
- correct
- correctAfterIncorrect
- incorrect

on many different lists of questionHistories including:
- a poor performing student example
- a strong preforming student example
- an improving student example

**Comment by vkumar825** [comment]
6/8/2021

- Took 1 hour to implement findQuestionsCorrect method
- Took 30 mins to implement findQuestionsIncorrect method
- Took 1 hour to implement findQuestionsCorrectAfterIncorrect method

6/9/2021

- Took 1 hr 30 mins to fix the flawed code for each of the methods.
  - checked for blank responses (added findBlanks method)
  - compared each answer to the correct answer properly
  - modified the tests to test blanks in poor and improving student.
