### ISSUE TITLE
front-end component to show hardcoded useful info from QuestionHistorySummary

### ISSUE THREAD

**Issue by tobydragon** [tobydragon/PAR#393]
How-to demo:

- Show a page that displays the following:
  - Display questions responded out of the total (with %)
  - Show how many questions correct (with %)
  - Show how many questions incorrect (with %)
  - Show how many questions correct after incorrect (with %)

Note: 
correct, incorrect, and correct after incorrect should add up to respondedTo

**Comment by vkumar825** [comment]
- 6/24/21:
  - I spent about 2 hours trying to figure out how to implement methods to detect correct answers, incorrect answers, total questions given a list of questions (with id, text, answer, and correctAnswer) but was unable to make any progress on these things

  - Will still need to review more about React, particularly more about Hooks, for lists, etc.

**Comment by vkumar825** [comment]
- 6/27/21:
  - Spent about 1 and a half hours working on this component. With the right idea on what to show for the component, I am able to display the number of questions answered out of the total, questions correct, incorrect, and correctAfterIncorrect.
