### ISSUE TITLE
Modify questionChooserBOC to make it convertible to json

### ISSUE THREAD

**Issue by embieck** [tobydragon/PAR#403]

**Comment by embieck** [comment]
How to demo:

- par ui can run with byOrder cohort in defaultCohorts.json 
- byOrder can be selected as a cohort
- student is suggested questions in student view after successfully being added to the cohort

**Comment by tobydragon** [comment]
have the chooser in the cohort json keep the list of concepts in order

Theoretically, you could leave a concept out of the list in cohort, and no questions would be asked about that concept

Similarly, if there is a concept in the list, and there are no questions about it, no questions will be asked, but it also won't be broken (might get stuck on that missing concept (next concept in list will be unprepared)

demo with different cohorts with different lists
