### ISSUE TITLE
create api call to get QuestionHistorySummary

### ISSUE THREAD

**Issue by vkumar825** [tobydragon/PAR#404]
how-to demo:

api call that can get questions idsSeen, respondedTo, questionsCorrectFirstTie, questionsIncorrect, and questionsCorrectAfterIncorrect.

returns a list that contains these variables.

**Comment by tobydragon** [comment]
need to know what are the inputs:
- studentId

returns an object containing those things
 - QuestionHistorySummary object would have to be convertable to json 
    - data members public
    - default constructor 
    - tested (toAndFromJson tests)

functions at:
  - controller level - tested (relies on good spring testing)
  - server level
  - studentModel level - tested

**Comment by vkumar825** [comment]
Time took: 3 hours

Issue:

- I have been having issues trying to read in the QuestionHistorySummary given a studentId, and a student JSON file (ex. o1)
- I get the error "Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token"
- Even modifying the student JSON to change and remove certain things still gives a problem, such as UnrecognizedPropertyException: Unrecognized field
The aforementioned problems occurs when the student json file is filled with information that are received from the stuentView question responses area.

This issue doesn't seem to pop up in earlier branches before QuestionChooserByOrderedConcepts (branch that has been merged with QuestionHistorySummary) based on the indication of ToAndFromJson test in StudentModelDatasourceJsonTest.

**Comment by vkumar825** [comment]
**The above issue has been resolved.**
