### ISSUE TITLE
Make front end responsive through Bootstrap

### ISSUE THREAD

**Issue by EMurtaghh** [tobydragon/PAR#43]

**Comment by EMurtaghh** [comment]
For mobile conversion, breakpoints on all cols at XS breakpoint.
iPad, use md or s breakpoints on all cols for displau.

**Comment by timothymarotta** [comment]
@tobydragon I wonder if this card is even relevant anymore now that we're planning for React

**Comment by kerryannebuckman** [comment]
@timothymarotta I was just about to ask you if it is. I can't remember what you and Toby were saying in our most recent meeting.
