### ISSUE TITLE
Front End Problems

### ISSUE THREAD

**Issue by CryptoGraphicDragon** [tobydragon/PAR#51]

**Comment by EMurtaghh** [comment]
Image URL in ReadImageTask, giving problems with finding image due to JSON and string reading constraints.
3 hours

**Comment by CryptoGraphicDragon** [comment]
2 hours, trying to make check answers work again

**Comment by CryptoGraphicDragon** [comment]
2 hours making images work right

**Comment by EMurtaghh** [comment]
2 hours getting submit to work after multiple imageTasks
