### ISSUE TITLE
nextImageTask should use a studentModel rather than a userQuestionSet

### ISSUE THREAD

**Issue by kerryannebuckman** [tobydragon/PAR#87]
Done when:
 - studentModel is a parameter of nextImageTask();
 - nextImageTask() uses the student model's level in order to pick the appropriate questions/number of questions

**Comment by JohnHunter809** [comment]
- How should taskGenerator handle a studentModel that has no unseenQuestions?

**Comment by JohnHunter809** [comment]
3 hrs: Making the Task Generator, fixing up the rest of the system

**Comment by JohnHunter809** [comment]
1 hr: finializing, doing a pull request
