### ISSUE TITLE
Combine all Question Files into one complete file

### ISSUE THREAD

**Issue by JohnHunter809** [tobydragon/PAR#92]
Done when: there is one file that has a complete list of demo questions
-response files have updated question ids
-all tests involving question files use this new file

**Comment by JohnHunter809** [comment]
2 hrs:
- Deleting unnecessary files, refactoring their usages throughout the system

**Comment by kerryannebuckman** [comment]
3 hours

DELETED FILES:
 - SampleQuestions.json
 - SampleQuestions2.json
 - SampleQuestionsSameDifficulty.json

FILES NEEDED:
 - SampleQuestionPool.json
 - SampleQuestionPool2.json (added. Used in userQuestionSetEqualsTest. Used to use SampleQuestions2.json)
 - SampleResponses.json     //matches SampleQuestionPool.json
 - ImageTask Objects written in json for the sake of comparison:
     - nextmageTaskTest1.json
     - nextmageTaskTest2.json
     - SampleImageTaskSingleQuestion.json
     - SampleImageTaskSingleQuestion3.json   // labeled with 3 because the second intended image task is made but only for assertedNotNull, not assertEquals, so the json for SampleImageTaskSingleQuestion2 is unnecessary
 - SampleQuestionsEmpty.json

TBD, still in project:
 - SampleStudentModelBusy.json
 - SampleStudentModelRecordList.json 
 - SampleStudentModelRecordList1.json

**Comment by kerryannebuckman** [comment]
- SampleStudentModelBusy.json
 - SampleStudentModelRecordList.json
 - SampleStudentModelRecordList1.json

All needed, remaining in the project
